site_name: rucula-js
nav:
  - Compreendendo: 
    - Janelas: compreendendo/janelas.md
    - Frames: compreendendo/frames.md
    - Alias: compreendendo/alias.md
    - Fields: compreendendo/fields.md
    - Layout: compreendendo/layout.md
    - Eventos: compreendendo/eventos.md
    - Urls: compreendendo/urls.md
    - Botões: compreendendo/botoes.md
    - Terminal: compreendendo/terminal.md
  - Configurações Globais:
    - Configurações Globais: configuracoesGlobais.md
    - Ambientes: ambiente.md
    - Localizações: localizacoes.md
  - Api:
    - Janelas: api/janelas.md
    - Frames: api/frames.md
    - Fields: api/fields.md
    - Botões: api/botoes.md

theme:
  name: material
  
extra_css:
  - ./css/extra-style.css

extra:
  analytics:
    provider: google
    property: G-GXRGLZL4NE
  