site_name: rucula-js
nav:
  - Introdução: index.md
  - Começando:
    - O que é?: comecando/o-que-e-o-rucula-js.md
    - Como Configurar?: comecando/como-configurar.md
    - Hello World: comecando/hello-world.md
  - Compreendendo: 
    - Unidades Cliente/Servidor: compreendendo/unidades-logicas-interligadas.md
    - Unidades das Janelas: compreendendo/unidades-das-janelas.md
    - Janelas: compreendendo/janelas.md
    - Frames: compreendendo/frames.md
    - Alias: compreendendo/alias.md
    - Layout: compreendendo/layout.md
    - Fields: compreendendo/fields.md
    - Terminal: compreendendo/terminal.md
    - Grids: compreendendo/grids.md
    - Eventos: compreendendo/eventos.md
    - Urls: compreendendo/urls.md
    - End Points: compreendendo/endPoints.md
    - Botões: compreendendo/botoes.md
  - Guia do Usuario:  
    - Consumindo a API via CEP com evento de campo : guia-usuario/viacep-com-evento-de-campo.md
    - Trabalhando com Atalhos: guia-usuario/Atalhos.md
  - Desenvolvendo:
    - Roadmap: desenvolvendo/roadmap.md
    - Criando a Janela: desenvolvendo/janelas.md
  - Configurações Globais:
    - Configurações Globais: configuracoesGlobais.md
    - Ambientes: ambiente.md
    - Localizações: localizacoes.md
  - Api:
    - Frames: api/frames.md
    - Botões: api/botoes.md
    - Objetos: api/objetos.md

theme:
  name: material
  
extra_css:
  - ./css/extra-style.css

extra:
  analytics:
    provider: google
    property: G-GXRGLZL4NE
  