name: deploy documentação
run-name: manutenção do site
on: [push]
jobs:
  Deploy-Mkdocs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.0.0
      
      - uses: actions/setup-python@v4.7.0
      - run: pip install mkdocs  
      - run: pip install mkdocs-material

      - run: mkdocs build
        working-directory: docs
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/site/

      - uses: actions/checkout@v4.0.0
        with:
          repository: 'rucula-js/rucula-js.github.io'
          
      - uses: actions/download-artifact@v2
        with:
          name: docs
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
        
          
