name: deploy documentação
run-name: manutenção do site
on: [push]
jobs:
  Deploy-Mkdocs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4.7.0
      - run: pip install mkdocs  
      - run: pip install mkdocs-material

      - run: mkdocs build
        working-directory: docs
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/site/

      - uses: actions/checkout@v4.0.0
        with:
          repository: 'rucula-js.github.io'

      - run: ls -R
      
      #- uses: actions/download-artifact@v2
      #  with:
      #    name: docs
      #    path: docs/teste/doc

      #- run: ls -R
      #  working-directory: docs/teste/doc
      
