name: deploy documentação
run-name: manutenção do site
on: [push]
jobs:
  Deploy-Mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4.7.0
      - run: pip install mkdocs  
      - run: pip install mkdocs-material
      - run: mkdocs build
        working-directory: docs
        
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/site/
          
      - name: Generate a token
        id: generate_token  
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.DOCS_APP_ID }}
          private_key: ${{ secrets.DOCS_PK }}  
          
      - uses: actions/checkout@v4.0.0
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          repository: rucula-js/rucula-js.github.io
          persist-credentials: false
          
      - uses: actions/download-artifact@v2
        with:
          name: docs

      - run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      #- run: gh auth login --with-token ${{ steps.generate_token.outputs.token }}
      - run: gh auth login status









      
