name: deploy documentação
run-name: manutenção do site
on: [push]
jobs:
  Deploy-Mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4.7.0
      - run: pip install mkdocs  
      - run: pip install mkdocs-material
      - run: mkdocs build
        working-directory: docs
        
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/site/
          
      - name: Generate a token
        id: generate_token  
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.DOCS_APP_ID }}
          private_key: ${{ secrets.DOCS_PK }}  
          
      - uses: actions/checkout@v4.0.0
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          repository: rucula-js/rucula-js.github.io
          persist-credentials: false
          
      - uses: actions/download-artifact@v2
        with:
          name: docs
      - run: git push
