name: Unit Test
run-name: Unit Test
on: 
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0    
    - name: Install Node 
    - uses: actions/setup-node@v4.0.3
    - name: Install Dependency
    - run: npm install
    - name: Run Test
    - run: npm run test

