name: Unit Test
run-name: Unit Test
on: 
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0
    
    - name: Install node
      uses: actions/setup-node@v4.0.3
    
    - name: Install dependencies
      run: npm install

    - name: Run Test
    - run: npm run test

